project_id = "ytaporbcmtlidafbssyc"

[functions.chat]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.send-access-approval]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.seo-engine-generate]
verify_jwt = false

[functions.seo-engine-scheduler]
verify_jwt = false

[functions.seo-engine-validate]
verify_jwt = false

[functions.auto-blog]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.create-product-checkout]
verify_jwt = false

[functions.stripe-subscription-webhook]
verify_jwt = false

[functions.verify-order]
verify_jwt = false

[functions.create-mcf-order]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.send-expiry-notice]
verify_jwt = false

[functions.send-trial-reminder]
verify_jwt = false

[functions.sync-amazon-inventory]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false
