project_id = "ytaporbcmtlidafbssyc"

[functions.chat]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.send-access-approval]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.seo-engine-generate]
verify_jwt = false

[functions.seo-engine-scheduler]
verify_jwt = false

[functions.seo-engine-validate]
verify_jwt = false
